import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>세상의 모든 차</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      세상의 모든 차
    </>
  )
}
